In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split

## Testing Classification

In [10]:
dataset = pd.read_csv('data/classification/heart.csv')
dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [11]:
X = dataset.drop(columns='target', axis=1)
Y = dataset['target']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [12]:
# pip install ubml
from ubml.train_test import classification_train_test
classification_train_test(x_train=X_train, y_train=Y_train, x_test=X_test, y_test=Y_test)

,Accuracy Score train,Accuracy Score test,F1 Score train,F1 Score test,Recall Score train,Recall Score test,Jaccard Score train,Jaccard Score test,Precision Score train,Precision Score test
Logistic Regression,0.852,0.805,0.863,0.823,0.903,0.886,0.758,0.699,0.826,0.769
KNN Classifier,0.906,0.722,0.907,0.722,0.893,0.705,0.830,0.565,0.922,0.740
SVM Classifier,0.721,0.707,0.741,0.732,0.777,0.781,0.588,0.577,0.708,0.689
Naive Bayes Classifier,0.839,0.780,0.848,0.791,0.874,0.810,0.736,0.654,0.823,0.773
Decision Tree Classifier,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
Random Forest Classifier,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

## Testing Regression

In [2]:
dataset = pd.read_csv('data/regression/car_dataset.csv')
dataset.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,0,0,0,0
1,sx4,2013,4.75,9.54,43000,1,0,0,0
2,ciaz,2017,7.25,9.85,6900,0,0,0,0
3,wagon r,2011,2.85,4.15,5200,0,0,0,0
4,swift,2014,4.60,6.87,42450,1,0,0,0

In [3]:
X = dataset.drop(['Car_Name','Selling_Price'],axis=1)
Y = dataset['Selling_Price']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, random_state=2)

In [5]:
# pip install ubml
from ubml.train_test import regression_train_test
regression_train_test(x_train=X_train, y_train=Y_train, x_test=X_test, y_test=Y_test)

,r2 score train,r2 score test,MSE train,MSE test,RMSE train,RMSE test,MAE train,MAE test,Explained Variance Score train,Explained Variance Score test,Max Error train,Max Error test
Linear Regression,0.880,0.837,3.259,2.150,1.805,1.466,1.217,1.152,0.880,0.846,11.078,3.975
Lasso Regression,0.843,0.871,4.268,1.698,2.066,1.303,1.286,1.051,0.843,0.871,12.380,3.281
Ridge Regression,0.880,0.840,3.260,2.104,1.806,1.450,1.213,1.143,0.880,0.849,11.113,3.884
Support Vector Regression,-0.078,0.109,29.252,11.729,5.409,3.425,3.236,2.679,-0.003,0.161,31.218,9.118
Decision Tree Regression,1.000,0.953,0.000,0.623,0.000,0.789,0.000,0.462,1.000,0.953,0.000,3.000
Random Forest Regression,0.988,0.982,0.327,0.234,0.572,0.484,0.240,0.330,0.988,0.983,5.852,1.297